### PR TITLE
Remove NSG 19B Features Extents Tests and Other Issues

### LINKED ISSUE #12: N S G_ CRSdefinitions Test - java.lang.NoClassDefFoundError: org/geotools/util/UnsupportedImplementationException
Attached is a tiled geopackage with a 4326 SRS. The definition used is :+1: 

GEOGCS["WGS84",DATUM["WGS_1984",SPHEROID["WGS84",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]]

I am receiving the error in the title, but I am fairly confident the definition is correct. When I run the code locally using my own geotools sources the definition is parsed correctly and can be used. When running it through the test suite I get this issue :

N S G_ CRSdefinitions Test - java.lang.NoClassDefFoundError: org/geotools/util/UnsupportedImplementationException

This would appear to be an issue with the test suite. Attached is the geopackage I used for testing.

[BlackMarble-NSG2.1.gpkg.zip](https://github.com/opengeospatial/ets-gpkg12-nsg/files/1903784/BlackMarble-NSG2.1.gpkg.zip)

### PR DESCRIPTION
**Pull request by ajanett**
Removed the feature related extents tests (NSG 19B) from NSG_DataContentsTests as these will be contained in the OGC features tests.

Moved the tile related extents tests (NSG 19B)  from NSG_DataContentsTests into the NSG_TileTests because this will allow them to be skipped if this no tile data.
At this point, there is nothing left in NSG_DataContentsTests, so it is removed.
SpatialReferenceSystemsTests:
   There seem to be several issues here and being unable to address them all, I've moved some of the issues into the LOG.
   Firstly, these tests fail when there is no gpkg_tile_matrix table, which is often the case in a features-only geopackage. So I added a test to first ensure the table is present before running the test.
   Next, the call to parseWKT is triggering an exception that is not a FactoryException but rather an exception due to a casting problem. I added a catch section to record this exception to the LOG rather than trigger a failure so that the rest of the tests can be run.  Comments have been placed into the code where this casting exception is triggered.  In addition to this exception catch, added additional catch segments to identify additional errors.
These changes address issues:
#10 – fix
#12 (closed) – this is still an issue, these code changes include comments and exception catch code and log entries to try and help identify the issue.

### CODE REVIEW

**Comment by ajanett** [comment]
Please find attached geopackages for testing:
  
PR_FeaTest_PASS_NSG.gpkg
Passes all tests. This is a small, feature-only geopackage
However, reports:
org.opengis.cite.gpkg12.nsg.core.NSG_SpatialReferenceSystemsTests crsDefinitionsTests  WARNING: The gpkg_spatial_ref_sys table could not be examined for IDs due to processing exception.

PR_FeaTest_FAIL_NSG_SRS_Desc.gpkg
[Gpkg-12-nsg-testCases.zip](https://github.com/opengeospatial/ets-gpkg12-nsg/files/2073521/Gpkg-12-nsg-testCases.zip)
Fails NSG Req 19-A: The gpkg_spatial_ref_sys table contains invalid descriptions for IDs: 4326
Also reports: 
org.opengis.cite.gpkg12.nsg.core.NSG_SpatialReferenceSystemsTests crsDefinitionsTests  WARNING: The gpkg_spatial_ref_sys table could not be examined for IDs due to processing exception.

**Comment by dstenger** [comment]
@keshav-nangare 
Can you please resolve the merge conflicts?

**Comment by dstenger** [comment]
@ajanett 

Is the test failure of "NSG Req 19-A" with "PR_FeaTest_FAIL_NSG_SRS_Desc.gpkg" (https://github.com/opengeospatial/ets-gpkg12-nsg/pull/24#issuecomment-394811820) expected? If this behaviour is unexpected, we should open a new issue for that.

**Comment by keshav-nangare** [comment]
Conflicts resolved in PR: https://github.com/opengeospatial/ets-gpkg12-nsg/pull/25

**Comment by ajanett** [comment]
@dstenger Yeah, this is kind of my question on this one. I am not really sure if that test case is supposed to fail or not, which is why I included it for review here. The SRS description is one created by the GDAL GeoPackage creation utility. Granted, the SRS description is not EXACTLY like the one specified in the NSG specification, but it looked to me like all of the correct keywords were specified as they should be. It was only when I copied the exact SRS description out of the NSG specification and pasted it into the GeoPackage that I could get a pass on this test... and that is what I did to create the "PR_FeaTest_PASS_NSG.gpkg" test case.  I appreciate your looking into this and I agree that it should be listed as a separate issue if, indeed, it is determined to be a problem. 

So the SRS ID 4326

Here is the content in the failing GeoPackage:
**definition:**
GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]
**description:**
longitude/latitude coordinates in decimal degrees on the WGS 84 spheroid

Here is the content in the passing GeoPackage:
**definition:**
GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS84",6378137,298.257223563,]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]]
**description:**
Horizontal component of 3D system. Used by the GPS satellite navigation system and for NATO military geodetic surveying.

**Comment by lgoltz** [comment]
Replaced by #25

**Pull request closed without merging**
